#!/usr/bin/env sh
set -eu

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

mkdir -p dist
cat > dist/jelly.js <<'ENTRY'
/* Auto-generated by npm run build. Do not edit directly. */
import "../src/jelly.js";
ENTRY

echo "Built dist/jelly.js"
